apiVersion: v1
kind: Service
metadata:
  annotations:
  name: cloud-prediction
  namespace: overstory
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: cloud-prediction
  sessionAffinity: None
  type: NodePort
